// code generated by pbf v4.0.1

exports.readBlob = readBlob;
function readBlob(pbf, end) {
    return pbf.readFields(readBlobField, {raw: undefined, raw_size: 0, zlib_data: undefined, lzma_data: undefined, OBSOLETE_bzip2_data: undefined}, end);
}
function readBlobField(tag, obj, pbf) {
    if (tag === 1) obj.raw = pbf.readBytes();
    else if (tag === 2) obj.raw_size = pbf.readVarint(true);
    else if (tag === 3) obj.zlib_data = pbf.readBytes();
    else if (tag === 4) obj.lzma_data = pbf.readBytes();
    else if (tag === 5) obj.OBSOLETE_bzip2_data = pbf.readBytes();
}
exports.writeBlob = writeBlob;
function writeBlob(obj, pbf) {
    if (obj.raw != null) pbf.writeBytesField(1, obj.raw);
    if (obj.raw_size) pbf.writeVarintField(2, obj.raw_size);
    if (obj.zlib_data != null) pbf.writeBytesField(3, obj.zlib_data);
    if (obj.lzma_data != null) pbf.writeBytesField(4, obj.lzma_data);
    if (obj.OBSOLETE_bzip2_data != null) pbf.writeBytesField(5, obj.OBSOLETE_bzip2_data);
}

exports.readBlobHeader = readBlobHeader;
function readBlobHeader(pbf, end) {
    return pbf.readFields(readBlobHeaderField, {type: "", indexdata: undefined, datasize: 0}, end);
}
function readBlobHeaderField(tag, obj, pbf) {
    if (tag === 1) obj.type = pbf.readString();
    else if (tag === 2) obj.indexdata = pbf.readBytes();
    else if (tag === 3) obj.datasize = pbf.readVarint(true);
}
exports.writeBlobHeader = writeBlobHeader;
function writeBlobHeader(obj, pbf) {
    if (obj.type) pbf.writeStringField(1, obj.type);
    if (obj.indexdata != null) pbf.writeBytesField(2, obj.indexdata);
    if (obj.datasize) pbf.writeVarintField(3, obj.datasize);
}
