// code generated by pbf v4.0.1

exports.readHeaderBlock = readHeaderBlock;
function readHeaderBlock(pbf, end) {
    return pbf.readFields(readHeaderBlockField, {bbox: undefined, required_features: [], optional_features: [], writingprogram: "", source: "", osmosis_replication_timestamp: 0, osmosis_replication_sequence_number: 0, osmosis_replication_base_url: ""}, end);
}
function readHeaderBlockField(tag, obj, pbf) {
    if (tag === 1) obj.bbox = readHeaderBBox(pbf, pbf.readVarint() + pbf.pos);
    else if (tag === 4) obj.required_features.push(pbf.readString());
    else if (tag === 5) obj.optional_features.push(pbf.readString());
    else if (tag === 16) obj.writingprogram = pbf.readString();
    else if (tag === 17) obj.source = pbf.readString();
    else if (tag === 32) obj.osmosis_replication_timestamp = pbf.readVarint(true);
    else if (tag === 33) obj.osmosis_replication_sequence_number = pbf.readVarint(true);
    else if (tag === 34) obj.osmosis_replication_base_url = pbf.readString();
}
exports.writeHeaderBlock = writeHeaderBlock;
function writeHeaderBlock(obj, pbf) {
    if (obj.bbox) pbf.writeMessage(1, writeHeaderBBox, obj.bbox);
    if (obj.required_features) for (const item of obj.required_features) pbf.writeStringField(4, item);
    if (obj.optional_features) for (const item of obj.optional_features) pbf.writeStringField(5, item);
    if (obj.writingprogram) pbf.writeStringField(16, obj.writingprogram);
    if (obj.source) pbf.writeStringField(17, obj.source);
    if (obj.osmosis_replication_timestamp) pbf.writeVarintField(32, obj.osmosis_replication_timestamp);
    if (obj.osmosis_replication_sequence_number) pbf.writeVarintField(33, obj.osmosis_replication_sequence_number);
    if (obj.osmosis_replication_base_url) pbf.writeStringField(34, obj.osmosis_replication_base_url);
}

exports.readHeaderBBox = readHeaderBBox;
function readHeaderBBox(pbf, end) {
    return pbf.readFields(readHeaderBBoxField, {left: 0, right: 0, top: 0, bottom: 0}, end);
}
function readHeaderBBoxField(tag, obj, pbf) {
    if (tag === 1) obj.left = pbf.readSVarint();
    else if (tag === 2) obj.right = pbf.readSVarint();
    else if (tag === 3) obj.top = pbf.readSVarint();
    else if (tag === 4) obj.bottom = pbf.readSVarint();
}
exports.writeHeaderBBox = writeHeaderBBox;
function writeHeaderBBox(obj, pbf) {
    if (obj.left) pbf.writeSVarintField(1, obj.left);
    if (obj.right) pbf.writeSVarintField(2, obj.right);
    if (obj.top) pbf.writeSVarintField(3, obj.top);
    if (obj.bottom) pbf.writeSVarintField(4, obj.bottom);
}

exports.readPrimitiveBlock = readPrimitiveBlock;
function readPrimitiveBlock(pbf, end) {
    return pbf.readFields(readPrimitiveBlockField, {stringtable: undefined, primitivegroup: [], granularity: 0, lat_offset: 0, lon_offset: 0, date_granularity: 0}, end);
}
function readPrimitiveBlockField(tag, obj, pbf) {
    if (tag === 1) obj.stringtable = readStringTable(pbf, pbf.readVarint() + pbf.pos);
    else if (tag === 2) obj.primitivegroup.push(readPrimitiveGroup(pbf, pbf.readVarint() + pbf.pos));
    else if (tag === 17) obj.granularity = pbf.readVarint(true);
    else if (tag === 19) obj.lat_offset = pbf.readVarint(true);
    else if (tag === 20) obj.lon_offset = pbf.readVarint(true);
    else if (tag === 18) obj.date_granularity = pbf.readVarint(true);
}
exports.writePrimitiveBlock = writePrimitiveBlock;
function writePrimitiveBlock(obj, pbf) {
    if (obj.stringtable) pbf.writeMessage(1, writeStringTable, obj.stringtable);
    if (obj.primitivegroup) for (const item of obj.primitivegroup) pbf.writeMessage(2, writePrimitiveGroup, item);
    if (obj.granularity) pbf.writeVarintField(17, obj.granularity);
    if (obj.lat_offset) pbf.writeVarintField(19, obj.lat_offset);
    if (obj.lon_offset) pbf.writeVarintField(20, obj.lon_offset);
    if (obj.date_granularity) pbf.writeVarintField(18, obj.date_granularity);
}

exports.readPrimitiveGroup = readPrimitiveGroup;
function readPrimitiveGroup(pbf, end) {
    return pbf.readFields(readPrimitiveGroupField, {nodes: [], dense: undefined, ways: [], relations: [], changesets: []}, end);
}
function readPrimitiveGroupField(tag, obj, pbf) {
    if (tag === 1) obj.nodes.push(readNode(pbf, pbf.readVarint() + pbf.pos));
    else if (tag === 2) obj.dense = readDenseNodes(pbf, pbf.readVarint() + pbf.pos);
    else if (tag === 3) obj.ways.push(readWay(pbf, pbf.readVarint() + pbf.pos));
    else if (tag === 4) obj.relations.push(readRelation(pbf, pbf.readVarint() + pbf.pos));
    else if (tag === 5) obj.changesets.push(readChangeSet(pbf, pbf.readVarint() + pbf.pos));
}
exports.writePrimitiveGroup = writePrimitiveGroup;
function writePrimitiveGroup(obj, pbf) {
    if (obj.nodes) for (const item of obj.nodes) pbf.writeMessage(1, writeNode, item);
    if (obj.dense) pbf.writeMessage(2, writeDenseNodes, obj.dense);
    if (obj.ways) for (const item of obj.ways) pbf.writeMessage(3, writeWay, item);
    if (obj.relations) for (const item of obj.relations) pbf.writeMessage(4, writeRelation, item);
    if (obj.changesets) for (const item of obj.changesets) pbf.writeMessage(5, writeChangeSet, item);
}

exports.readStringTable = readStringTable;
function readStringTable(pbf, end) {
    return pbf.readFields(readStringTableField, {s: []}, end);
}
function readStringTableField(tag, obj, pbf) {
    if (tag === 1) obj.s.push(pbf.readBytes());
}
exports.writeStringTable = writeStringTable;
function writeStringTable(obj, pbf) {
    if (obj.s) for (const item of obj.s) pbf.writeBytesField(1, item);
}

exports.readInfo = readInfo;
function readInfo(pbf, end) {
    return pbf.readFields(readInfoField, {version: 0, timestamp: 0, changeset: 0, uid: 0, user_sid: 0, visible: false}, end);
}
function readInfoField(tag, obj, pbf) {
    if (tag === 1) obj.version = pbf.readVarint(true);
    else if (tag === 2) obj.timestamp = pbf.readVarint(true);
    else if (tag === 3) obj.changeset = pbf.readVarint(true);
    else if (tag === 4) obj.uid = pbf.readVarint(true);
    else if (tag === 5) obj.user_sid = pbf.readVarint();
    else if (tag === 6) obj.visible = pbf.readBoolean();
}
exports.writeInfo = writeInfo;
function writeInfo(obj, pbf) {
    if (obj.version) pbf.writeVarintField(1, obj.version);
    if (obj.timestamp) pbf.writeVarintField(2, obj.timestamp);
    if (obj.changeset) pbf.writeVarintField(3, obj.changeset);
    if (obj.uid) pbf.writeVarintField(4, obj.uid);
    if (obj.user_sid) pbf.writeVarintField(5, obj.user_sid);
    if (obj.visible) pbf.writeBooleanField(6, obj.visible);
}

exports.readDenseInfo = readDenseInfo;
function readDenseInfo(pbf, end) {
    return pbf.readFields(readDenseInfoField, {version: [], timestamp: [], changeset: [], uid: [], user_sid: [], visible: []}, end);
}
function readDenseInfoField(tag, obj, pbf) {
    if (tag === 1) pbf.readPackedVarint(obj.version, true);
    else if (tag === 2) pbf.readPackedSVarint(obj.timestamp);
    else if (tag === 3) pbf.readPackedSVarint(obj.changeset);
    else if (tag === 4) pbf.readPackedSVarint(obj.uid);
    else if (tag === 5) pbf.readPackedSVarint(obj.user_sid);
    else if (tag === 6) pbf.readPackedBoolean(obj.visible);
}
exports.writeDenseInfo = writeDenseInfo;
function writeDenseInfo(obj, pbf) {
    if (obj.version) pbf.writePackedVarint(1, obj.version);
    if (obj.timestamp) pbf.writePackedSVarint(2, obj.timestamp);
    if (obj.changeset) pbf.writePackedSVarint(3, obj.changeset);
    if (obj.uid) pbf.writePackedSVarint(4, obj.uid);
    if (obj.user_sid) pbf.writePackedSVarint(5, obj.user_sid);
    if (obj.visible) pbf.writePackedBoolean(6, obj.visible);
}

exports.readChangeSet = readChangeSet;
function readChangeSet(pbf, end) {
    return pbf.readFields(readChangeSetField, {id: 0}, end);
}
function readChangeSetField(tag, obj, pbf) {
    if (tag === 1) obj.id = pbf.readVarint(true);
}
exports.writeChangeSet = writeChangeSet;
function writeChangeSet(obj, pbf) {
    if (obj.id) pbf.writeVarintField(1, obj.id);
}

exports.readNode = readNode;
function readNode(pbf, end) {
    return pbf.readFields(readNodeField, {id: 0, keys: [], vals: [], info: undefined, lat: 0, lon: 0}, end);
}
function readNodeField(tag, obj, pbf) {
    if (tag === 1) obj.id = pbf.readSVarint();
    else if (tag === 2) pbf.readPackedVarint(obj.keys);
    else if (tag === 3) pbf.readPackedVarint(obj.vals);
    else if (tag === 4) obj.info = readInfo(pbf, pbf.readVarint() + pbf.pos);
    else if (tag === 8) obj.lat = pbf.readSVarint();
    else if (tag === 9) obj.lon = pbf.readSVarint();
}
exports.writeNode = writeNode;
function writeNode(obj, pbf) {
    if (obj.id) pbf.writeSVarintField(1, obj.id);
    if (obj.keys) pbf.writePackedVarint(2, obj.keys);
    if (obj.vals) pbf.writePackedVarint(3, obj.vals);
    if (obj.info) pbf.writeMessage(4, writeInfo, obj.info);
    if (obj.lat) pbf.writeSVarintField(8, obj.lat);
    if (obj.lon) pbf.writeSVarintField(9, obj.lon);
}

exports.readDenseNodes = readDenseNodes;
function readDenseNodes(pbf, end) {
    return pbf.readFields(readDenseNodesField, {id: [], denseinfo: undefined, lat: [], lon: [], keys_vals: []}, end);
}
function readDenseNodesField(tag, obj, pbf) {
    if (tag === 1) pbf.readPackedSVarint(obj.id);
    else if (tag === 5) obj.denseinfo = readDenseInfo(pbf, pbf.readVarint() + pbf.pos);
    else if (tag === 8) pbf.readPackedSVarint(obj.lat);
    else if (tag === 9) pbf.readPackedSVarint(obj.lon);
    else if (tag === 10) pbf.readPackedVarint(obj.keys_vals, true);
}
exports.writeDenseNodes = writeDenseNodes;
function writeDenseNodes(obj, pbf) {
    if (obj.id) pbf.writePackedSVarint(1, obj.id);
    if (obj.denseinfo) pbf.writeMessage(5, writeDenseInfo, obj.denseinfo);
    if (obj.lat) pbf.writePackedSVarint(8, obj.lat);
    if (obj.lon) pbf.writePackedSVarint(9, obj.lon);
    if (obj.keys_vals) pbf.writePackedVarint(10, obj.keys_vals);
}

exports.readWay = readWay;
function readWay(pbf, end) {
    return pbf.readFields(readWayField, {id: 0, keys: [], vals: [], info: undefined, refs: []}, end);
}
function readWayField(tag, obj, pbf) {
    if (tag === 1) obj.id = pbf.readVarint(true);
    else if (tag === 2) pbf.readPackedVarint(obj.keys);
    else if (tag === 3) pbf.readPackedVarint(obj.vals);
    else if (tag === 4) obj.info = readInfo(pbf, pbf.readVarint() + pbf.pos);
    else if (tag === 8) pbf.readPackedSVarint(obj.refs);
}
exports.writeWay = writeWay;
function writeWay(obj, pbf) {
    if (obj.id) pbf.writeVarintField(1, obj.id);
    if (obj.keys) pbf.writePackedVarint(2, obj.keys);
    if (obj.vals) pbf.writePackedVarint(3, obj.vals);
    if (obj.info) pbf.writeMessage(4, writeInfo, obj.info);
    if (obj.refs) pbf.writePackedSVarint(8, obj.refs);
}

exports.readRelation = readRelation;
function readRelation(pbf, end) {
    return pbf.readFields(readRelationField, {id: 0, keys: [], vals: [], info: undefined, roles_sid: [], memids: [], types: []}, end);
}
function readRelationField(tag, obj, pbf) {
    if (tag === 1) obj.id = pbf.readVarint(true);
    else if (tag === 2) pbf.readPackedVarint(obj.keys);
    else if (tag === 3) pbf.readPackedVarint(obj.vals);
    else if (tag === 4) obj.info = readInfo(pbf, pbf.readVarint() + pbf.pos);
    else if (tag === 8) pbf.readPackedVarint(obj.roles_sid, true);
    else if (tag === 9) pbf.readPackedSVarint(obj.memids);
    else if (tag === 10) pbf.readPackedVarint(obj.types);
}
exports.writeRelation = writeRelation;
function writeRelation(obj, pbf) {
    if (obj.id) pbf.writeVarintField(1, obj.id);
    if (obj.keys) pbf.writePackedVarint(2, obj.keys);
    if (obj.vals) pbf.writePackedVarint(3, obj.vals);
    if (obj.info) pbf.writeMessage(4, writeInfo, obj.info);
    if (obj.roles_sid) pbf.writePackedVarint(8, obj.roles_sid);
    if (obj.memids) pbf.writePackedSVarint(9, obj.memids);
    if (obj.types) pbf.writePackedVarint(10, obj.types);
}

const RelationMemberType = exports.RelationMemberType = {
    "NODE": 0,
    "WAY": 1,
    "RELATION": 2
};
